// <auto-generated />
using API.PROTESTO.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace API.PROTESTO.Migrations
{
    [DbContext(typeof(ProtestoContext))]
    partial class ProtestoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("API.PROTESTO.Models.Protesto", b =>
                {
                    b.Property<int>("ProtestoID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro_Devedor");

                    b.Property<string>("CEP_Devedor");

                    b.Property<string>("CPF_CNPJ_Devedor");

                    b.Property<string>("Cidade_Devedor");

                    b.Property<string>("Cidade_Praca_Pagamento");

                    b.Property<string>("CodigoBanco");

                    b.Property<string>("CodigoInterno");

                    b.Property<string>("DataEmissao");

                    b.Property<string>("DataVencimento");

                    b.Property<string>("Endereco_Devedor");

                    b.Property<string>("NomeCredor");

                    b.Property<string>("NomeDevedor");

                    b.Property<string>("NumeroTitulo");

                    b.Property<string>("Operacao");

                    b.Property<string>("Parcela");

                    b.Property<string>("QtdeParcelaContrato");

                    b.Property<string>("TipoDocumento");

                    b.Property<string>("UF_Devedor");

                    b.Property<string>("UF_Praca_Pagamento");

                    b.Property<string>("Valor1aParcela");

                    b.Property<string>("ValorProtestar");

                    b.Property<string>("ValorTitulo");

                    b.HasKey("ProtestoID");

                    b.ToTable("Protestos");
                });
#pragma warning restore 612, 618
        }
    }
}
